#!/bin/bash

# labextensions
jupyter labextension install --clean @jupyter-widgets/jupyterlab-manager \
                                      @jupyterlab/server-proxy \
                                      dask-labextension

# Error installing vscode extensions, comment out for now:
# Extension 'ms-python.python' not found.
# Make sure you use the full extension ID, including the publisher, e.g.: ms-vscode.csharp
# error undefined
#code-server --install-extension ms-python.python

# Install the VS code proxy - move to start script for use on hubs (since /home/jovyan has NFS mount)
pip install --no-cache git+git://github.com/betatim/vscode-binder#egg=jupyter_vscode_proxy

# EOF
